###
POST http://localhost:3000/api
Content-Type: application/json

{
    "your JSON object goes here": "your JSON object goes here"
}
###
GET http://localhost:3000/api/8995426191440

###
PUT http://localhost:3000/api/8995426191440

Content-Type: application/json
{
    "your JSON object goes here": "your JSON object goes here"
}

###
DELETE http://localhost:3000/api/8995426191440