###
POST http://localhost:3000/api
Content-Type: application/json

{
    "your JSON object goes here": "your JSON object goes here"
}
###
GET http://localhost:3000/api/164945740870323250

###
PUT http://localhost:3000/api/164945740870323250
Content-Type: application/json

{
    "your JSON object goes here": "Jumba BUns"
}

###
DELETE http://localhost:3000/api/164945740870323250